### ISSUE TITLE
build error on Ubuntu 13.10 (Saucy)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yinheli/lightweight-java-profiler#3]
```
lightweight-java-profiler fails to build on Ubuntu 13.10 (Saucy):

/home/adam/src/lightweight-java-profiler/src/display.cc:23:22: error: invalid 
suffix on literal; C++11 requires a space between literal and identifier 
[-Werror=literal-suffix]
       fprintf(file_, "%"PRIdPTR" ", traces[i].count);

The fix is trivial; patch attached.
```

Original issue reported on code.google.com by `a...@medovina.org` on 5 Oct 2013 at 8:46

Attachments:
- [build_fix.diff](https://storage.googleapis.com/google-code-attachments/lightweight-java-profiler/issue-3/comment-0/build_fix.diff)
